const data = {
    products : [
        {
            _id:'1',
            name: 'Impresora 3D Flsun tipo Delta',
            category: 'Impresion 3D',
            image: '/img/3d.png',
            price : '4.100.000',
            rating: 4.5,
            numReviews: 10,
            description:'La impresora 3D mas rapido del mercado',
        },

        {
            _id:'2',
            name: 'Amplificador tipo D 2X100W',
            category: 'Amplificadores de audio',
            image: '/img/amplificador100w.png',
            price : '130.000',
            rating: 4.5,
            numReviews: 10,
            description:'Entrada auxiliar, bluetooth y microSD',
        },
        {
            _id:'3',
            name: 'Modulo Bluetooth Mp3 USB radio 6-12v',
            category: 'Amplificadores de audio',
            image: '/img/frontal.png',
            price : '30.000',
            rating: 4.5,
            numReviews: 10,
            description:'Entrada Auxiliar, bluetooth, microSD, Radio',
        },
        {
            _id:'4',
            name: 'Modulo Relevo con control RF',
            category: 'Modulos',
            image: '/img/rfrele.png',
            price : '38.000',
            rating: 4.5,
            numReviews: 10,
            description:'Activa y desactiva a distacia todos tus dipositivos desde un control remoto',
        },
        {
            _id:'5',
            name: 'Bobina de Tesla',
            category: 'Modulos',
            image: '/img/tesla.png',
            price : '25.000',
            numReviews: 10,
            description:'Kit educativo para armar ',
        },
        {
            _id:'6',
            name: 'Variador de voltaje AC 110-220VAC',
            category: 'Variadores de voltaje',
            price : '25.000',
            image: '/img/variadorac.png',
            rating: 4.5,
            numReviews: 10,
            description:'Hasta 15 amperios',
        },
    ],
};
export default data;